// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Polo.Shop.Persistence;

namespace Polo.Shop.Persistence.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20220415140439_ChangeAddressListToReadonlyListAndAddScoreToCustomer")]
    partial class ChangeAddressListToReadonlyListAndAddScoreToCustomer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Polo.Shop.CustomerContext.Domain.CustomerAggregate.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("UniqueIdentifier");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("VarChar")
                        .HasMaxLength(500);

                    b.Property<int>("CityId")
                        .HasColumnType("Int");

                    b.Property<string>("Coordinate")
                        .HasColumnType("VarChar")
                        .HasMaxLength(30);

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("UniqueIdentifier");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("VarChar")
                        .HasMaxLength(10);

                    b.Property<string>("Telephone")
                        .HasColumnType("VarChar")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Address","CustomerContext");
                });

            modelBuilder.Entity("Polo.Shop.CustomerContext.Domain.CustomerAggregate.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("UniqueIdentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVarChar")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("NVarChar")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("NVarChar")
                        .HasMaxLength(50);

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("Char")
                        .HasMaxLength(10);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVarChar")
                        .HasMaxLength(50);

                    b.Property<int>("Score")
                        .HasColumnType("Int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer","CustomerContext");
                });

            modelBuilder.Entity("Polo.Shop.CustomerContext.Domain.CustomerAggregate.Address", b =>
                {
                    b.HasOne("Polo.Shop.CustomerContext.Domain.CustomerAggregate.Customer", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
