//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polo.Shop.CustomerContext.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polo.Shop.CustomerContext.Resources.ExceptionResource", typeof(ExceptionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادرس را وارد کنید.
        /// </summary>
        public static string AddressLineRequiredException {
            get {
                return ResourceManager.GetString("AddressLineRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل را درست وارد کنید.
        /// </summary>
        public static string CheckEmailPatternException {
            get {
                return ResourceManager.GetString("CheckEmailPatternException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل را وارد کنید.
        /// </summary>
        public static string EmailRequiredException {
            get {
                return ResourceManager.GetString("EmailRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام را وارد کنید.
        /// </summary>
        public static string FirstNameRequiredException {
            get {
                return ResourceManager.GetString("FirstNameRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی را وارد کنید.
        /// </summary>
        public static string LastNameRequiredException {
            get {
                return ResourceManager.GetString("LastNameRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدملی باید یکتا باشد.
        /// </summary>
        public static string NationalCodeDublicationException {
            get {
                return ResourceManager.GetString("NationalCodeDublicationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی را وارد کنید.
        /// </summary>
        public static string NationalCodeRequiredException {
            get {
                return ResourceManager.GetString("NationalCodeRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسورد باید حداقل 8 حرف باشد.
        /// </summary>
        public static string PasswordLengthValidationException {
            get {
                return ResourceManager.GetString("PasswordLengthValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسورد را وارد کنید.
        /// </summary>
        public static string PasswordRequiredException {
            get {
                return ResourceManager.GetString("PasswordRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پستی را وارد کنید.
        /// </summary>
        public static string PostalCodeRequiredException {
            get {
                return ResourceManager.GetString("PostalCodeRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری را وارد کنید.
        /// </summary>
        public static string UserNameRequiredException {
            get {
                return ResourceManager.GetString("UserNameRequiredException", resourceCulture);
            }
        }
    }
}
